### ISSUE TITLE
I have 71 Moderator Mail Messages, but I have read them all.

### ISSUE THREAD

**Issue by PFCKrutonium** [BoringCode/RedditNotifier#37]
The plugin is always telling me I have 71 messages, no matter what I do. And to be clear, I do in fact have more than 71 mod mails, but it's always 71 new, even when none are new.

**Comment by BoringCode** [comment]
Moderator mail has always had issues with marking the messages as read. This is a reddit thing. It is only marked as read if you click on the message itself.

The addon is pulling its data from https://www.reddit.com/message/moderator/unread.json. Visit this link while logged in and you should see the raw message data. If you don't have any unread messages it should be very short.

If there aren't any messages listed there, please let me know. There may be an issue with the addon itself. But otherwise, this is an old reddit issue. If this is annoying, I would recommend turning off moderator messages in the RedditNotifier settings panel.

**Comment by PFCKrutonium** [comment]
Ah okay, thank you, that cleared it up! Thanks for the reply :+1:
